##### physical model parameters
# susceptibility
#chi0 = 10.0 
chi0 = 1.0E4
# depth of stress shadow
#depthS = -0.2
depthS = -0.5E0
# loading function to be used
use_loading = "step"
# use_loading = "4points"
# use_loading = "background"

##### starting state
# initial stress shadow , usually set to zero
Sshadow = 0.0
equilibrium = false

##### discretisation parameter
# sample interval in seconds (default 12 minutes)
deltat = 720
# start time in seconds (default 0 seconds)
tstart = 0
# end time in seconds (default 24 hours)
tend = 86_400

# sampling of coulomb stress axis
#deltaS = 0.01
#deltaS = -depthS/40.
deltaS = 0.0125
# range to sample
#sigma_max = 10.0
#sigma_max = 2000.*deltaS
sigma_max = 25.0
# precision
#precision = 12
precision = 18

##### stress loading models
[loading]
  # step function overlaying steady stressing rate
  [loading.4points]
    # fist phase must be larger at least 2
    n1 = 50          
    # second phase at least n1+1, better n1+2 as central differences taken
    n2 = 51          
    # coulomb stress values
    sc0 = 0.0        
    sc1 = 0.5E0
    sc2 = 1.0E0
    sc3 = 2.0E0
  # step function overlaying steady stressing rate
  [loading.step]
    # strend (background stress rate (=DeltaS/deltat)
    #strend = 0.00001
    strend = 7.0E-5
    # time of step in seconds (tstart < tstep < tend)
    # default: tend / 2
    # tstep = 40_000  
    # coulomb stress step 
    sstep = 1.0E0
  # cyclic sinusoidal ooading added to background stress rate
  [loading.cycle]
    # strend (background stress rate (=DeltaS/deltat)
    strend = 7.0E-5
    ampsin = 0.2E0
    Tsin   = 43_200
  # background loading 
  [loading.background]
    # strend (background stress rate (=DeltaS/deltat)
    #strend = 0.00001
    strend = 7.0E-5
