name: docs

on: [push]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
            - run: |
                  pip install pipenv
                  pipenv install --dev

            - name: Build docs
              run: |
                  invoke docs --no-serve
                  touch docs/_build/html/.nojekyll

            - name: Deploy to pages
              uses: JamesIves/github-pages-deploy-action@3.7.1
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: gh-pages
                  FOLDER: docs/_build/html/
                  CLEAN: true
